### ISSUE TITLE
"Name is required" when trying to create stager

### ISSUE THREAD

**Issue by TKX42** [PhoenixC2/PhoenixC2#50]
# Description
Cant create new stager because there is no name input.

# Reproduction
1. Go to 'Stagers'
2. Click on 'Create a new stager'
3. Click on 'Create'

# Expected behavior
Option to enter a name

# Screenshots/Output (Optional)
![image](https://github.com/PhoenixC2/PhoenixC2/assets/49553574/c66c1339-7475-450c-a195-61eccd83cb47)

**Comment by lucahennemann** [comment]
Hello Tristan, thank you for creating this issue. I am currently rebuilding the frontend in react, so i won't fix the issue, as i am going to remove the current frontend in the new release. You can find the new frontend here: https://github.com/PhoenixC2/Frontend but it is not finished yet. Hope i could help you and stay tuned for the new frontend :)

**Comment by effyxt** [comment]
goat
