### ISSUE TITLE
whats the username and password

### ISSUE THREAD

**Issue by shaheedghazi** [PhoenixC2/PhoenixC2#56]
upon executing it gives a key and says it created a super user
i dont know whats the user name and password

**Comment by lucahennemann** [comment]
When you start the executable for the first time, it should show the generated admin credentials. If they were not displayed, you can run `phserver --recreate-super-user` to regenerate them.

**Comment by shaheedghazi** [comment]
Oh, let me retry thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shaheedghazi** [comment]
poetry run phserver --recreate-super-user
resolved
