### ISSUE TITLE
can't create stager

### ISSUE THREAD

**Issue by r3dm4t3** [PhoenixC2/PhoenixC2#79]
Can't create a stagers
When I try, "name is required"
But where I can write it???

**Comment by lucahennemann** [comment]
Hello @r3dm4t3 as stated in https://github.com/PhoenixC2/PhoenixC2/issues/50#issuecomment-1554836677 and other closed issues, the current state of the front end is unfinished. I'm currently not working on this project, so you will either have to use the unstable v.1.1 branch and install the new front end as a plugin, which is not documented right now. I hope i could still help you, and i am sorry to for not working on this project in the moment.

**Comment by effyxt** [comment]
skill issue
